path:
    data: /elasticsearch/data
    logs: /elasticsearch/log
    plugins: /elasticsearch/plugins
    work: /elasticsearch/work
  
http:
    cors:
        allow-origin: "/.*/"
        allow-credentials: true
        enabled: true